openapi: 3.0.0
info:
  title: TODOリスト_API
  version: 1.0.0

paths:
  /users/login:
    post:
      summary: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin@exapmle.com
                password:
                  type: string
                  example: password
            example:
              name: admin@exapmle.com
              password: password


      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
      security:
        - ApiKeyAuth: []
  /todos:
    # 今日のTODOリストの取得
    get:
      summary: 今日のTODOリスト取得
      responses:
        '200':
          description: 今日のTODOリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todos'
                  example:
                    - id: 1
                      description: "OpenAPI学習"
                      is_daily: false
                      is_completed: false
                    - id: 2
                      description: "Next.js学習"
                      is_daily: true
                      is_completed: true
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
  /todos/stats:
    get:
      summary: 今日のTODO達成率取得
      responses:
        '200':
          description: TODO達成率
          content:
            application/json:
              schema:
                type: object
                properties:
                  rate:
                    type: number
              example:
                rate: 100
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

components:
  schemas:
    # ユーザー情報のスキーマ
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
    # TODOリストのスキーマ
    Todos: 
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Todo"
    Todo:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        is_daily:
          type: boolean
        is_completed:
          type: boolean
    # エラーのスキーマ
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
